export type SourceCategory = "Fintech Blogs" | "Big Tech Blogs";
export type SourceKind = "rss" | "google_news" | "bing_news" | "html";

export type NewsSource = {
  id: string;
  name: string;
  company: string;
  category: SourceCategory;
  kind: SourceKind;
  sourceUrl: string;
  feedUrl: string;
  alternateFeedUrls?: string[];
  includePatterns?: string[];
  excludePatterns?: string[];
};

function googleNewsUrl(query: string) {
  const encoded = encodeURIComponent(query);
  return `https://news.google.com/rss/search?q=${encoded}&hl=en-US&gl=US&ceid=US:en`;
}

function officialGoogleFallback(domainOrPath: string, topic: string) {
  return googleNewsUrl(`site:${domainOrPath} ${topic}`);
}

export const sources: NewsSource[] = [
  {
    id: "sofi-press",
    name: "SoFi Press",
    company: "SoFi",
    category: "Fintech Blogs",
    kind: "rss",
    sourceUrl: "https://www.sofi.com/press/",
    feedUrl: "https://investors.sofi.com/rss/news-releases.xml",
    alternateFeedUrls: [
      officialGoogleFallback("investors.sofi.com/news/Press-Releases", "SoFi"),
      officialGoogleFallback("investors.sofi.com", "SoFi press release"),
      officialGoogleFallback("sofi.com/press", "SoFi"),
    ],
    includePatterns: ["investors.sofi.com/news/", "investors.sofi.com/rss/", "www.sofi.com/press/"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "toast-product-news",
    name: "Toast POS Product News",
    company: "Toast",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://pos.toasttab.com/news?types=product-news",
    feedUrl: "https://pos.toasttab.com/news?types=product-news",
    alternateFeedUrls: [officialGoogleFallback("pos.toasttab.com/news", "Toast product news")],
    includePatterns: ["pos.toasttab.com/news", "pos.toasttab.com/blog"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "marqeta-blog",
    name: "Marqeta Blog",
    company: "Marqeta",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.marqeta.com/blog",
    feedUrl: "https://www.marqeta.com/blog",
    alternateFeedUrls: [officialGoogleFallback("marqeta.com/blog", "Marqeta")],
    includePatterns: ["marqeta.com/blog"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "block-investor-news",
    name: "Block Investor News",
    company: "Block",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://investors.block.xyz/investor-news/default.aspx",
    feedUrl: "https://investors.block.xyz/investor-news/default.aspx",
    alternateFeedUrls: [officialGoogleFallback("investors.block.xyz/investor-news", "Block investor news")],
    includePatterns: ["investors.block.xyz/investor-news", "investors.block.xyz/news"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "affirm-news",
    name: "Affirm News",
    company: "Affirm",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://investors.affirm.com/news-events/all-news",
    feedUrl: "https://investors.affirm.com/news-events/all-news",
    alternateFeedUrls: [officialGoogleFallback("investors.affirm.com/news-events", "Affirm")],
    includePatterns: ["investors.affirm.com/news-events", "investors.affirm.com/news"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "shift4-news",
    name: "Shift4 News",
    company: "Shift4",
    category: "Fintech Blogs",
    kind: "rss",
    sourceUrl: "https://www.shift4.com/news",
    feedUrl: "https://investors.shift4.com/news-events/press-releases/rss",
    alternateFeedUrls: [officialGoogleFallback("investors.shift4.com/news-events/press-releases", "Shift4")],
  },
  {
    id: "adyen-newsroom",
    name: "Adyen Newsroom",
    company: "Adyen",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.adyen.com/press-and-media/newsroom",
    feedUrl: "https://www.adyen.com/press-and-media",
    alternateFeedUrls: [officialGoogleFallback("adyen.com/press-and-media/newsroom", "Adyen")],
    includePatterns: ["/press-and-media/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "shopify-pressroom",
    name: "Shopify Pressroom",
    company: "Shopify",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://news.shopify.com/",
    feedUrl: "https://news.shopify.com/",
    alternateFeedUrls: [officialGoogleFallback("news.shopify.com", "Shopify")],
    includePatterns: ["news.shopify.com/"],
    excludePatterns: ["?", "#", "/tags/", "/search"],
  },
  {
    id: "nubank-newsroom",
    name: "Nubank Newsroom",
    company: "Nubank",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://international.nubank.com.br/newsroom/",
    feedUrl: "https://international.nubank.com.br/newsroom/",
    alternateFeedUrls: [officialGoogleFallback("international.nubank.com.br/newsroom", "Nubank")],
    includePatterns: ["international.nubank.com.br/newsroom"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "paypal-newsroom",
    name: "PayPal Newsroom",
    company: "PayPal",
    category: "Fintech Blogs",
    kind: "rss",
    sourceUrl: "https://newsroom.paypal-corp.com/news",
    feedUrl: "https://newsroom.paypal-corp.com/news?pagetemplate=rss",
    alternateFeedUrls: [officialGoogleFallback("newsroom.paypal-corp.com/news", "PayPal")],
  },
  {
    id: "robinhood-blog",
    name: "Robinhood Blog",
    company: "Robinhood",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://blog.robinhood.com/",
    feedUrl: "https://blog.robinhood.com/",
    alternateFeedUrls: [officialGoogleFallback("blog.robinhood.com", "Robinhood")],
    includePatterns: ["blog.robinhood.com", "robinhood.com/us/en/newsroom"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "coinbase-blog",
    name: "Coinbase Blog",
    company: "Coinbase",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://blog.coinbase.com/",
    feedUrl: "https://www.coinbase.com/blog",
    alternateFeedUrls: [officialGoogleFallback("coinbase.com/blog", "Coinbase")],
    includePatterns: ["blog.coinbase.com", "coinbase.com/blog"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "upstart-press",
    name: "Upstart Press Releases",
    company: "Upstart",
    category: "Fintech Blogs",
    kind: "rss",
    sourceUrl: "https://www.upstart.com/news/press-releases/",
    feedUrl: "https://ir.upstart.com/rss/news-releases.xml",
    alternateFeedUrls: [officialGoogleFallback("upstart.com/news/press-releases", "Upstart")],
    includePatterns: ["/news/", "/press-releases/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "wise-newsroom",
    name: "Wise Newsroom",
    company: "Wise",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://newsroom.wise.com/en-NAM/",
    feedUrl: "https://newsroom.wise.com/en-NAM/",
    alternateFeedUrls: [officialGoogleFallback("newsroom.wise.com/en-NAM", "Wise")],
    includePatterns: ["newsroom.wise.com/en-NAM/"],
    excludePatterns: ["?", "#", "/tags/"],
  },
  {
    id: "klarna-press",
    name: "Klarna International Newsroom",
    company: "Klarna",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.klarna.com/international/press/",
    feedUrl: "https://www.klarna.com/international/press/",
    alternateFeedUrls: [officialGoogleFallback("klarna.com/international/press", "Klarna")],
    includePatterns: ["/international/press/"],
    excludePatterns: ["?", "#", "/categories/", "/category/", "/tag/", "/tags/"],
  },
  {
    id: "dave-press",
    name: "Dave Press",
    company: "Dave",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://dave.com/press",
    feedUrl: "https://dave.com/press",
    alternateFeedUrls: [officialGoogleFallback("dave.com/press", "Dave")],
    includePatterns: ["dave.com/press", "dave.com/newsroom"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "galileo-blog",
    name: "Galileo Technologies Blog",
    company: "Galileo",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.galileo-ft.com/blog/",
    feedUrl: "https://www.galileo-ft.com/blog/",
    alternateFeedUrls: [officialGoogleFallback("galileo-ft.com/blog", "Galileo")],
    includePatterns: ["galileo-ft.com/blog", "galileo-ft.com/news"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "chime-newsroom",
    name: "Chime Newsroom",
    company: "Chime",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.chime.com/newsroom/",
    feedUrl: "https://www.chime.com/newsroom/",
    alternateFeedUrls: [officialGoogleFallback("chime.com/newsroom", "Chime")],
    includePatterns: ["chime.com/newsroom"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "circle-pressroom",
    name: "Circle Pressroom",
    company: "Circle",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.circle.com/pressroom",
    feedUrl: "https://www.circle.com/pressroom",
    alternateFeedUrls: [officialGoogleFallback("circle.com/pressroom", "Circle")],
    includePatterns: ["/pressroom/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "dlocal-blog",
    name: "dLocal Blog",
    company: "dLocal",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.dlocal.com/blog/",
    feedUrl: "https://www.dlocal.com/blog/",
    alternateFeedUrls: [officialGoogleFallback("dlocal.com/blog", "dLocal")],
    includePatterns: ["/blog/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "nvidia-newsroom",
    name: "NVIDIA Newsroom",
    company: "NVIDIA",
    category: "Big Tech Blogs",
    kind: "rss",
    sourceUrl: "https://nvidianews.nvidia.com/news/latest",
    feedUrl: "https://nvidianews.nvidia.com/rss.xml",
    alternateFeedUrls: [officialGoogleFallback("nvidianews.nvidia.com/news", "NVIDIA")],
  },
  {
    id: "datadog-investor-news",
    name: "Datadog Investor News",
    company: "Datadog",
    category: "Big Tech Blogs",
    kind: "rss",
    sourceUrl: "https://investors.datadoghq.com/news-releases",
    feedUrl: "https://investors.datadoghq.com/rss/news-releases.xml",
    alternateFeedUrls: [
      officialGoogleFallback("investors.datadoghq.com/news-releases", "Datadog"),
      officialGoogleFallback("datadoghq.com", "Datadog press release"),
    ],
  },
  {
    id: "tesla-blog",
    name: "Tesla Blog",
    company: "Tesla",
    category: "Big Tech Blogs",
    kind: "html",
    sourceUrl: "https://www.tesla.com/blog",
    feedUrl: "https://www.tesla.com/blog",
    alternateFeedUrls: [officialGoogleFallback("tesla.com/blog", "Tesla")],
    includePatterns: ["tesla.com/blog"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "trade-desk-press-room",
    name: "The Trade Desk Press Room",
    company: "The Trade Desk",
    category: "Big Tech Blogs",
    kind: "html",
    sourceUrl: "https://www.thetradedesk.com/us/news/press-room",
    feedUrl: "https://www.thetradedesk.com/us/news/press-room",
    alternateFeedUrls: [officialGoogleFallback("thetradedesk.com/us/news/press-room", "The Trade Desk")],
    includePatterns: ["/press-room/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "amazon-press-archive",
    name: "Amazon Press Archive",
    company: "Amazon",
    category: "Big Tech Blogs",
    kind: "html",
    sourceUrl: "https://press.aboutamazon.com/press-release-archive",
    feedUrl: "https://press.aboutamazon.com/press-release-archive",
    alternateFeedUrls: [officialGoogleFallback("press.aboutamazon.com/press-release-archive", "Amazon")],
    includePatterns: ["press.aboutamazon.com/"],
    excludePatterns: ["?", "#", "/press-release-archive", "/press-center-signup", "/images-and-videos", "/contact-us"],
  },
  {
    id: "google-blog",
    name: "Google Blog",
    company: "Google",
    category: "Big Tech Blogs",
    kind: "rss",
    sourceUrl: "https://blog.google/",
    feedUrl: "https://blog.google/rss/",
    alternateFeedUrls: [officialGoogleFallback("blog.google", "Google")],
  },
  {
    id: "about-amazon",
    name: "About Amazon",
    company: "Amazon",
    category: "Big Tech Blogs",
    kind: "rss",
    sourceUrl: "https://www.aboutamazon.com/",
    feedUrl: "https://www.aboutamazon.com/news/rss",
    alternateFeedUrls: [officialGoogleFallback("aboutamazon.com/news", "Amazon")],
  },
  {
    id: "tsmc-news",
    name: "TSMC Latest News",
    company: "TSMC",
    category: "Big Tech Blogs",
    kind: "html",
    sourceUrl: "https://pr.tsmc.com/english/latest-news",
    feedUrl: "https://pr.tsmc.com/english/latest-news",
    alternateFeedUrls: [
      officialGoogleFallback("pr.tsmc.com/english", "TSMC"),
      officialGoogleFallback("pr.tsmc.com", "TSMC English latest news"),
    ],
    includePatterns: ["pr.tsmc.com/english/news", "pr.tsmc.com/english/latest-news"],
    excludePatterns: ["?", "#"],
  },
];
