export type SourceCategory = "Fintech Blogs" | "Big Tech Blogs";
export type SourceKind = "rss" | "google_news" | "bing_news" | "html";

export type NewsSource = {
  id: string;
  name: string;
  company: string;
  category: SourceCategory;
  kind: SourceKind;
  sourceUrl: string;
  feedUrl: string;
  alternateFeedUrls?: string[];
  includePatterns?: string[];
  excludePatterns?: string[];
};

function googleNewsUrl(query: string) {
  const encoded = encodeURIComponent(query);
  return `https://news.google.com/rss/search?q=${encoded}&hl=en-US&gl=US&ceid=US:en`;
}

function bingNewsUrl(query: string) {
  const encoded = encodeURIComponent(query);
  return `https://www.bing.com/news/search?q=${encoded}&format=rss`;
}

export const sources: NewsSource[] = [
  {
    id: "sofi-press",
    name: "SoFi Press",
    company: "SoFi",
    category: "Fintech Blogs",
    kind: "bing_news",
    sourceUrl: "https://www.sofi.com/press/",
    feedUrl: bingNewsUrl("SoFi Technologies press release"),
    includePatterns: ["/press/"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "toast-product-news",
    name: "Toast POS Product News",
    company: "Toast",
    category: "Fintech Blogs",
    kind: "bing_news",
    sourceUrl: "https://pos.toasttab.com/news?types=product-news",
    feedUrl: bingNewsUrl("Toast POS product news"),
    alternateFeedUrls: [bingNewsUrl("Toast Inc news"), bingNewsUrl("Toast POS restaurant news")],
    includePatterns: ["/news/", "/blog/"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "marqeta-blog",
    name: "Marqeta Blog",
    company: "Marqeta",
    category: "Fintech Blogs",
    kind: "bing_news",
    sourceUrl: "https://www.marqeta.com/blog",
    feedUrl: bingNewsUrl("Marqeta blog"),
    includePatterns: ["/blog/"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "block-investor-news",
    name: "Block Investor News",
    company: "Block",
    category: "Fintech Blogs",
    kind: "google_news",
    sourceUrl: "https://investors.block.xyz/investor-news/default.aspx",
    feedUrl: googleNewsUrl('Block Inc Square (investor news OR newsroom OR "press release")'),
    includePatterns: ["/investor-news/", "/news/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "affirm-news",
    name: "Affirm News",
    company: "Affirm",
    category: "Fintech Blogs",
    kind: "google_news",
    sourceUrl: "https://investors.affirm.com/news-events/all-news",
    feedUrl: googleNewsUrl('Affirm Holdings (newsroom OR "press release" OR investor)'),
    includePatterns: ["/news-events/", "/news/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "shift4-news",
    name: "Shift4 News",
    company: "Shift4",
    category: "Fintech Blogs",
    kind: "rss",
    sourceUrl: "https://www.shift4.com/news",
    feedUrl: "https://investors.shift4.com/news-events/press-releases/rss",
  },
  {
    id: "adyen-newsroom",
    name: "Adyen Newsroom",
    company: "Adyen",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.adyen.com/press-and-media/newsroom",
    feedUrl: "https://www.adyen.com/press-and-media",
    includePatterns: ["/press-and-media/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "shopify-pressroom",
    name: "Shopify Pressroom",
    company: "Shopify",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://news.shopify.com/",
    feedUrl: "https://news.shopify.com/",
    includePatterns: ["news.shopify.com/"],
    excludePatterns: ["?", "#", "/tags/", "/search"],
  },
  {
    id: "nubank-newsroom",
    name: "Nubank Newsroom",
    company: "Nubank",
    category: "Fintech Blogs",
    kind: "bing_news",
    sourceUrl: "https://international.nubank.com.br/newsroom/",
    feedUrl: bingNewsUrl("Nubank newsroom"),
    includePatterns: ["/newsroom/"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "paypal-newsroom",
    name: "PayPal Newsroom",
    company: "PayPal",
    category: "Fintech Blogs",
    kind: "rss",
    sourceUrl: "https://newsroom.paypal-corp.com/news",
    feedUrl: "https://newsroom.paypal-corp.com/news?pagetemplate=rss",
  },
  {
    id: "robinhood-blog",
    name: "Robinhood Blog",
    company: "Robinhood",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://blog.robinhood.com/",
    feedUrl: "https://robinhood.com/us/en/newsroom/",
    includePatterns: ["/newsroom/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "coinbase-blog",
    name: "Coinbase Blog",
    company: "Coinbase",
    category: "Fintech Blogs",
    kind: "google_news",
    sourceUrl: "https://blog.coinbase.com/",
    feedUrl: googleNewsUrl('Coinbase (blog OR newsroom OR "press release")'),
    includePatterns: ["/blog/"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "upstart-press",
    name: "Upstart Press Releases",
    company: "Upstart",
    category: "Fintech Blogs",
    kind: "rss",
    sourceUrl: "https://www.upstart.com/news/press-releases/",
    feedUrl: "https://ir.upstart.com/rss/news-releases.xml",
    includePatterns: ["/news/", "/press-releases/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "wise-newsroom",
    name: "Wise Newsroom",
    company: "Wise",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://newsroom.wise.com/en-NAM/",
    feedUrl: "https://newsroom.wise.com/en-NAM/",
    includePatterns: ["newsroom.wise.com/en-NAM/"],
    excludePatterns: ["?", "#", "/tags/"],
  },
  {
    id: "klarna-press",
    name: "Klarna International Newsroom",
    company: "Klarna",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.klarna.com/international/press/",
    feedUrl: "https://www.klarna.com/international/press/",
    includePatterns: ["/international/press/"],
    excludePatterns: ["?", "#", "/categories/", "/category/", "/tag/", "/tags/"],
  },
  {
    id: "dave-press",
    name: "Dave Press",
    company: "Dave",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://dave.com/press",
    feedUrl: "https://dave.com/press",
    includePatterns: ["/press", "/newsroom"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "galileo-blog",
    name: "Galileo Technologies Blog",
    company: "Galileo",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.galileo-ft.com/blog/",
    feedUrl: "https://www.galileo-ft.com/news/",
    includePatterns: ["/news/", "/blog/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "chime-newsroom",
    name: "Chime Newsroom",
    company: "Chime",
    category: "Fintech Blogs",
    kind: "bing_news",
    sourceUrl: "https://www.chime.com/newsroom/",
    feedUrl: bingNewsUrl("Chime newsroom"),
    alternateFeedUrls: [bingNewsUrl("Chime Financial news"), bingNewsUrl("Chime fintech news")],
    includePatterns: ["/newsroom/"],
    excludePatterns: ["?", "#", "/tag/", "/tags/"],
  },
  {
    id: "circle-pressroom",
    name: "Circle Pressroom",
    company: "Circle",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.circle.com/pressroom",
    feedUrl: "https://www.circle.com/pressroom",
    includePatterns: ["/pressroom/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "dlocal-blog",
    name: "dLocal Blog",
    company: "dLocal",
    category: "Fintech Blogs",
    kind: "html",
    sourceUrl: "https://www.dlocal.com/blog/",
    feedUrl: "https://www.dlocal.com/blog/",
    includePatterns: ["/blog/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "nvidia-newsroom",
    name: "NVIDIA Newsroom",
    company: "NVIDIA",
    category: "Big Tech Blogs",
    kind: "rss",
    sourceUrl: "https://nvidianews.nvidia.com/news/latest",
    feedUrl: "https://nvidianews.nvidia.com/rss.xml",
  },
  {
    id: "datadog-investor-news",
    name: "Datadog Investor News",
    company: "Datadog",
    category: "Big Tech Blogs",
    kind: "rss",
    sourceUrl: "https://investors.datadoghq.com/news-releases",
    feedUrl: "https://investors.datadoghq.com/rss/news-releases.xml",
  },
  {
    id: "tesla-blog",
    name: "Tesla Blog",
    company: "Tesla",
    category: "Big Tech Blogs",
    kind: "bing_news",
    sourceUrl: "https://www.tesla.com/blog",
    feedUrl: bingNewsUrl("Tesla blog"),
    alternateFeedUrls: [bingNewsUrl("Tesla news"), bingNewsUrl("Tesla company news")],
    includePatterns: ["/blog/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "trade-desk-press-room",
    name: "The Trade Desk Press Room",
    company: "The Trade Desk",
    category: "Big Tech Blogs",
    kind: "html",
    sourceUrl: "https://www.thetradedesk.com/us/news/press-room",
    feedUrl: "https://www.thetradedesk.com/us/news/press-room",
    includePatterns: ["/press-room/"],
    excludePatterns: ["?", "#"],
  },
  {
    id: "amazon-press-archive",
    name: "Amazon Press Archive",
    company: "Amazon",
    category: "Big Tech Blogs",
    kind: "html",
    sourceUrl: "https://press.aboutamazon.com/press-release-archive",
    feedUrl: "https://press.aboutamazon.com/press-release-archive",
    includePatterns: ["press.aboutamazon.com/"],
    excludePatterns: ["?", "#", "/press-release-archive", "/press-center-signup", "/images-and-videos", "/contact-us"],
  },
  {
    id: "google-blog",
    name: "Google Blog",
    company: "Google",
    category: "Big Tech Blogs",
    kind: "rss",
    sourceUrl: "https://blog.google/",
    feedUrl: "https://blog.google/rss/",
  },
  {
    id: "about-amazon",
    name: "About Amazon",
    company: "Amazon",
    category: "Big Tech Blogs",
    kind: "rss",
    sourceUrl: "https://www.aboutamazon.com/",
    feedUrl: "https://www.aboutamazon.com/news/rss",
  },
  {
    id: "tsmc-news",
    name: "TSMC Latest News",
    company: "TSMC",
    category: "Big Tech Blogs",
    kind: "bing_news",
    sourceUrl: "https://pr.tsmc.com/english/latest-news",
    feedUrl: bingNewsUrl("TSMC latest news"),
    alternateFeedUrls: [bingNewsUrl("Taiwan Semiconductor Manufacturing news"), bingNewsUrl("TSMC press release")],
    includePatterns: ["/english/news/", "/english/latest-news"],
    excludePatterns: ["?", "#"],
  },
];
